--- 
apiVersion: v1
kind: Deployment
metadata:
  name: maven-app-deploy
spec:
  selector:
    matchLabels:
      app: maven-app
  template:
    metadata:
      labels:
        app: maven-app
    spec:
      containers:
      - name: maven-app-deploy
        image: bjgomes/maven:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8085

  