--- 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: maven-app-deploy
spec:
  replicas: 2 
  selector:
    matchLabels:
      app: maven-app
  template:
    metadata:
      labels:
        app: maven-app
    spec:
      containers:
      - name: maven-app-deploy
        image: bjgomes/maven:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8085
--- 
apiVersion: v1
kind: Service
metadata:
  name: maven-app-svc
spec:
  selector:
    app: maven-app
  ports:
    - protocol: TCP
      port: 8085
      targetPort: 8085
  type: LoadBalancer

  
  