apiVersion: apps/v1 
kind: Deployment
metadata:
  name: bjgomes-maven
  labels: 
     app: maven

spec:
  replicas: 2 
  selector:
    matchLabels:
      app: maven

  template:
    metadata:
      labels:
        app: maven
    spec:
      containers:
      - name: maven
        image: bjgomes/maven
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1