apiVersion: v1
kind: Service
metadata:
  name: maven-app
  labels:
    app: maven-app 
spec:
  selector:
    app: maven-app 
  type: LoadBalancer
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 31200
