apiVersion: v1
kind: Service
metadata:
  name: maven_app
  labels:
    app: maven_app 
spec:
  selector:
    app: maven_app 
  type: LoadBalancer
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 31200
